language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install coverage
  - pip install python-coveralls
script: "nosetests --with-coverage --cover-package=zenpy -v --stop"
